"""initial schema

Revision ID: c611ac8f6b4e
Revises: 
Create Date: 2026-09-08 06:44:21.212171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c611ac8f6b4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripture_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('client', 'coach', 'provider', 'church_admin', 'platform_admin', name='userrole'), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('phi_accessed', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('churches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('primary_contact_user_id', sa.UUID(), nullable=True),
    sa.Column('billing_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['primary_contact_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.Enum('psychiatrist', 'licensed_counselor', 'addiction_specialist', name='providertype'), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('license_state', sa.String(), nullable=False),
    sa.Column('npi_number', sa.String(), nullable=True),
    sa.Column('malpractice_verified', sa.Boolean(), nullable=True),
    sa.Column('vetting_status', sa.Enum('pending', 'in_review', 'approved', 'rejected', 'suspended', name='vettingstatus'), nullable=True),
    sa.Column('accepting_referrals', sa.Boolean(), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('scripture_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('verse_text', sa.Text(), nullable=False),
    sa.Column('reflection_text', sa.Text(), nullable=True),
    sa.Column('translation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['scripture_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coaches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('church_affiliation_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['church_affiliation_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=True),
    sa.Column('church_sponsor_id', sa.UUID(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('emergency_contact', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_sponsor_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('intake_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'triaged', 'closed', name='intakestatus'), nullable=True),
    sa.Column('distress_level', sa.Integer(), nullable=True),
    sa.Column('phq9_score', sa.Integer(), nullable=True),
    sa.Column('gad7_score', sa.Integer(), nullable=True),
    sa.Column('protective_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('presenting_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prayer_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roi_consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('discloses_to_provider_id', sa.UUID(), nullable=True),
    sa.Column('discloses_to_church_id', sa.UUID(), nullable=True),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('signature_hash', sa.String(), nullable=False),
    sa.Column('document_s3_key', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['discloses_to_church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['discloses_to_provider_id'], ['clinical_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['clinical_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsorships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('church_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('sponsor_type', sa.String(), nullable=True),
    sa.Column('sessions_covered', sa.Integer(), nullable=True),
    sa.Column('amount_covered_cents', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sponsorship_id', sa.UUID(), nullable=True),
    sa.Column('church_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['sponsorship_id'], ['sponsorships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intake_assessment_id', sa.UUID(), nullable=False),
    sa.Column('risk_type', sa.Enum('suicidal_ideation', 'substance_abuse', 'other_acute', name='risktype'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'moderate', 'high', 'imminent', name='riskseverity'), nullable=False),
    sa.Column('protocol_triggered', sa.Enum('safe_t', 'act_model', 'addiction_referral', 'none', name='protocoltriggered'), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['intake_assessment_id'], ['intake_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scripture_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('scripture_content_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('triggered_by_intake_id', sa.UUID(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['scripture_content_id'], ['scripture_content.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_intake_id'], ['intake_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('risk_event_id', sa.UUID(), nullable=True),
    sa.Column('consent_id', sa.UUID(), nullable=False),
    sa.Column('referral_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'completed', 'expired', name='referralstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['consent_id'], ['roi_consents.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['clinical_providers.id'], ),
    sa.ForeignKeyConstraint(['risk_event_id'], ['risk_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referrals')
    op.drop_table('session_notes')
    op.drop_table('scripture_deliveries')
    op.drop_table('risk_events')
    op.drop_table('invoices')
    op.drop_table('sponsorships')
    op.drop_table('sessions')
    op.drop_table('roi_consents')
    op.drop_table('prayer_requests')
    op.drop_table('intake_assessments')
    op.drop_table('clients')
    op.drop_table('coaches')
    op.drop_table('scripture_content')
    op.drop_table('clinical_providers')
    op.drop_table('churches')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('scripture_tags')
    # ### end Alembic commands ###

    # Alembic's autogenerate does not emit DROP TYPE for Postgres ENUM
    # columns (a known limitation), so downgrade() leaves orphaned enum
    # types behind unless we drop them explicitly here.
    for enum_name in (
        "userrole",
        "providertype",
        "vettingstatus",
        "intakestatus",
        "risktype",
        "riskseverity",
        "protocoltriggered",
        "referralstatus",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
